services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - reporter
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  reporter:
    build: .
    env_file: ".env"
    restart: always
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.reporting.schedule: "0 1,11,21,31,41,51 * * * *"
      ofelia.job-exec.reporting.command: 'python main.py'